Azure/Azure-Proactive-Resiliency-Library-v2

CODEOWNERS

Adding codeowners.
1. changes file: CODEOWNERS
NA

Patch codeowners 1

---

azure-resources/NetApp/netAppAccounts/kql/b2fb3e60-97ec-e34d-af29-b16a0d61c2ac.kql
azure-resources/NetApp/netAppAccounts/kql/e30317d2-c502-4dfe-a2d3-0a737cc79545.kql
azure-resources/NetApp/netAppAccounts/recommendations.yaml

Update netapp recommendation guid and add kql file
None
1. Swap guid for two netapp recommendations that were mismatched
2. Add kql file for recommendation that is missing its query
1. None

update netapp recommendation guid

---

azure-resources/Cdn/profiles/kql/1bd2b7e8-400f-e64a-99a2-c572f7b08a62.kql
azure-resources/Cdn/profiles/kql/38f3d542-6de6-a44b-86c6-97e3be690281.kql
azure-resources/DBforMySQL/flexibleServers/kql/88856605-53d8-4bbd-a75b-4a7b14939d32.kql
azure-resources/Network/azureFirewalls/kql/1b2dbf4a-8a0b-5e4b-8f4e-3f758188910d.kql
azure-resources/Network/azureFirewalls/kql/3c8fa7c6-6b78-a24a-a63f-348a7c71acb9.kql

Update two afw query recommendationIDs and other minor edits
None
1. Update two afw query recommendationIDs
2. Updates to Cdn and MySQL query comments
1. None

minor query updates

---

docs/archetypes/azure-resource-type/recommendations.yaml
docs/archetypes/azure-specialized-workload/recommendations.yaml
docs/content/contributing/create-content/create-recommendations/_index.md

Updates to contribution guide and archetypes to match YAML schema format for recommendations
N/A
1. Updates to contribution guide for yaml schema and layout
2. Updates to hugo archetypes for yaml schema
None

Updates to contribution guide and archetypes for yaml fields

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Updated Sign-off status for 2 additional Virtual Machine recommendations.
1. Sign-off status for 2 additional Virtual Machine recommendations.

Updated Sign-off status for 2 additional recommendations.

---

tools/1_wara_collector.ps1
tools/Version.json

Disabled Advisory Recommendations for now

Tooling: Collector 2.0.3

---

azure-resources/Compute/virtualMachineScaleSets/kql/457e1648-8aa2-214d-a854-11a4084ecdc9.kql
azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml

Updated VMSS based on PG sign-off.
1. Updated VMSS recommendations based on PG sign-off

Updated VMSS based on PG sign-off

---

CODEOWNERS
azure-waf/respond/_index.md
docs/archetypes/azure-waf/_index.md
docs/archetypes/azure-waf/recommendations.yaml
docs/content/contributing/create-content/add-dependent-azure-resources/_index.md
docs/content/contributing/create-content/create-archetypes/_index.md
docs/layouts/shortcodes/azure-resources-recommendationlist.html

Added WAF archetype and assocaited documentation, general guidance improvements, and fixed anchor link color
N/A
This pull request includes changes to various files to improve the documentation and recommendations of the Microsoft Azure Well-Architected Framework. The most important changes include refining the language used in the documentation, adding a new archetype for the framework, updating the recommendations template, and modifying the appearance of the recommendations list. This also fixes the codeowners file to require aprl-admin on all prs.
Language refinement:
* [`azure-waf/respond/_index.md`](diffhunk://#diff-432cb173600817ac7cd51519f2d8e9ecadea740ed11198ea2c2b892531b2622fL10-R10): Changed the language used to describe the final stage of the reliability process.
Addition of a …

Waf archetype and general fixes

---

tools/1_wara_collector.ps1
tools/Version.json

Updating on Collector Script
1. Bugfix when using -ResourceGroups

Tooling: Collector Script 2.0.4

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Azure Boost VM recommendations signed-off.
1. Updated verified status of Azure Boost VM recommendations for signed-off

Azure Boost VM recommendations signed-off

---

azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml

Updated long description of VMSS recommendation based on PG feedback.
1. Updated long description of VMSS recommendation on deprecated image versions.

Updated long description of VMSS recommendation.

---

azure-resources/AVS/privateClouds/recommendations.yaml

AVS Updated Monitoring configure to High
1. AVS Updated Monitoring configure to High

AVS Updated Monitoring configure to High

---

tools/1_wara_collector.ps1
tools/2_wara_data_analyzer.ps1
tools/3_wara_reports_generator.ps1
tools/Version.json

Critical Bugfix and general improvements
1. Bugfix on ResourceType filtering
2. Adding Subscription on ResourceType sheet
3. Improvement on Query processing speed
4. Inclusion of Resource Name and ID for Recommendations without ARG Queries
5. Bugfix on PPT Slide 21 processing with more than 9 Service Health Alerts
6. Highlighting of Recommendations without ARG Queries

Tooling Update

---

azure-resources/ContainerService/managedClusters/kql/26ebaf1f-c70d-4ebd-8641-4b60a0ce0094.kql
azure-resources/ContainerService/managedClusters/kql/4f63619f-5001-439c-bacb-8de891287727.kql
azure-resources/ContainerService/managedClusters/kql/a7bfcc18-b0d8-4d37-81f3-8131ed8bead5.kql
azure-resources/ContainerService/managedClusters/kql/ba3f7d17-9654-4038-b172-09f1b2569925.kql
azure-resources/ContainerService/managedClusters/recommendations.yaml

- Added query for AKS recommendations: 26ebaf1f-c70d-4ebd-8641-4b60a0ce0094, a7bfcc18-b0d8-4d37-81f3-8131ed8bead5 (Using Ephemeral Disks and Enabling Azure Policy)
- Added AKS recommendation and query: ba3f7d17-9654-4038-b172-09f1b2569925 (Private cluster or authorized IP ranges for cluster network resiliency)
1. Adds query for AKS recommendations: 26ebaf1f-c70d-4ebd-8641-4b60a0ce0094, a7bfcc18-b0d8-4d37-81f3-8131ed8bead5 (Using Ephemeral Disks and Enabling Azure Policy)
2. Adds AKS recommendation and query: ba3f7d17-9654-4038-b172-09f1b2569925 (Private cluster or authorized IP ranges for cluster network resiliency)

Update AKS recommendations

---

azure-resources/_index.md
azure-specialized-workloads/_index.md
azure-waf/_index.md
docs/content/tools/_index.md
docs/content/tools/script-overviews/_index.md

This pull request primarily focuses on two areas: adjusting the weight parameter in several markdown files and refining the instructions in the `script-overviews/_index.md` file. The weight parameter changes affect the order of sections in the documentation, while the adjustments to the instructions enhance clarity and readability.
Changes to weight parameters:
* [`azure-resources/_index.md`](diffhunk://#diff-cbf088537ba2ab979698d612e3560078180f4617626bda1b895b8d9d8e888ae0L3-R3): The weight parameter was reduced from 40 to 20, which may alter the order of this section in the documentation.
* [`azure-specialized-workloads/_index.md`](diffhunk://#diff-61479cccc6933258fe37ddb50978cb78790b76d32b26d69cea112f0660fab9f0L3-R3): The weight parameter was reduced from 40 to 30, which may alter the …

Tooling adjustments

---

docs/content/tools/_index.md

Fix Broken Link to ToC
1. Fix Broken Link to ToC
1. N/a

Tools Wiki - Fix Broken Link

---

docs/content/tools/_index.md

fix tools link

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Update VM APRL per Disk PM David Barber's request.
Replace this with a brief description of what this Pull Request fixes, changes, etc.
1. Mission Critical Workloads should consider using Premium or Ultra Disks
Impact: High …

Update VM APRL per Disk PM's request: Mission Critical Workloads 

---

.github/workflows/code-review.yml
azure-resources/DocumentDB/databaseAccounts/kql/23ebe97d-c546-204b-8b0d-00e61a5524f7.kql
azure-resources/DocumentDB/databaseAccounts/kql/43663217-a1d3-844b-80ea-571a2ce37c6c.kql
azure-resources/DocumentDB/databaseAccounts/kql/7eb32cf9-9a42-1540-acf8-597cbba8a418.kql
azure-resources/DocumentDB/databaseAccounts/kql/9cabded7-a1fc-6e4a-944b-d7dd98ea31a2.kql
azure-resources/DocumentDB/databaseAccounts/kql/9ce78192-74a0-104c-b5bb-9a443f941649.kql
azure-resources/DocumentDB/databaseAccounts/kql/c006604a-0d29-684c-99f0-9729cb40dac5.kql
azure-resources/DocumentDB/databaseAccounts/kql/deaea200-013c-414b-ac9f-bfa7a7fb13f0.kql
azure-resources/DocumentDB/databaseAccounts/kql/e544520b-8505-7841-9e77-1f1974ee86ec.kql
azure-resources/DocumentDB/databaseAccounts/kql/fa6ac22f-0584-bb4b-80e4-80f4755d1a97.kql
azure-resources/DocumentDB/databaseAccounts/recommendations.yaml

Add descriptions for Cosmos db link checks. Change PR Link tests to only test modified files.
N/A
1. Add descriptions for Cosmos db link checks. 
2. Change PR Link tests to only test modified files.
1. None

bugs-Cosmos-db-fixes and adjust setting for PR link tests

---

.github/scripts/validate-kql-comments.ps1

Adjust KQL script validation so we can actually see the filenames.

FIX: Changed Format-Table to Format-List

---

azure-resources/Databricks/workspaces/kql/8aa63c34-dd9d-49bd-9582-21ec310dfbdd.kql
azure-resources/Databricks/workspaces/recommendations.yaml

Revised guidance and control plane reference link to make investigation easier.
Fixes #107
* Updated recommendation
* Updated control plane doc link
* Updated ARG query to state it's not verifyable by ARG.
None

Revised legacy workspace migration guidance

---

docs/content/tools/script-overviews/_index.md

Fix download link for sample output of collector script
None
1. Fix collector script sample output download link
2. 
1. None

fix sample output download link

---

tools/2_wara_data_analyzer.ps1
tools/Version.json

BugFix on 2_wara_data_analyzer.ps1
1. Support Tickets sheet would present the wrong Support Ticket ID

Tooling: BugFix on Support Ticket ID

---

tools/1_wara_collector.ps1
tools/3_wara_reports_generator.ps1
tools/Version.json

Bugfixes on tooling scripts 1 and 3
#115   
1. Bugfix on missing validation for queries "under development" and "recommendation cannot be validated with ARGs"
2. Bugfix for typo at line 1337 on script: 3_wara_reports_generator.ps1

Tooling: Bugfixes on Missing Validations "under development" and typo at line 1337

---

azure-resources/Databricks/workspaces/recommendations.yaml

Revised recommendation title from "Migrate Legacy Workspaces" to "Evaluate regional isolation for workspaces"
Related to #107
1. #107
None

Revised databricks recommendation

---

azure-resources/Network/expressRouteCircuits/kql/f06a2bbe-5839-d447-9f39-fc3d20562d88.kql
azure-resources/Network/expressRouteCircuits/recommendations.yaml

Resolve issue 16
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues/16
Resolves #16 
For ER circuits:
- Update recommendations.yaml to change automationAvailable to no
- Change corresponding kql file to // cannot-be-validated-with-arg

Resolve issue #16 for ER circuit active/active guidance  - remove ARG query, update YAML

---

tools/1_wara_collector.ps1
tools/2_wara_data_analyzer.ps1
tools/Version.json

Support for Specialized Workloads and Code Improvements on "1_wara_collector" and "2_wara_data_analyzer"
#68 
1. Adds support for the Specialized Workloads (SAP, AVD, HPC and AVS)
2. Starts to align the code to Microsoft's recommendation

Tooling: Support for Specialized Workloads and Code Improvement

---

azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml

Changed VM Disk recommendation from SSD to Premium or Ultra Disks.
Customers should be advised to choose based on perf and availability requirements of a given workload.
1. Changed VM Disk recommendation from SSD to Premium or Ultra Disks.

Changed VM Disk recommendation from SSD to Premium or Ultra Disks

---

azure-resources/Network/loadBalancers/recommendations.yaml

This PR updates the language for the Load Balancer Health Probe guidance to address the issue reported in #20.  
fixes #20 
1. Updates guidance on LB health probe configurations.  Addresses issue #20 
1. No breaking changes.
- [ x] Read the [Contribution …

Updated LB probe language

---

azure-resources/NetApp/netAppAccounts/kql/8bb690e8-64d5-4838-8703-9ee3dbac688f.kql
azure-resources/NetApp/netAppAccounts/recommendations.yaml

Updated ANF APRL related to Availability Zone based on feedback from Sean Luce and Igor Pagliai.
A. Use availability zones for high availability in Azure NetApp Files: High Availability (specifically at the application level)
B. Enable Cross-zone replication of Azure NetApp Files volumes: Disaster Recovery
C.<New> Deploy ANF volumes in the same availability zone with Azure compute and other services: Other Best Practices 
- To associate an ADO Work Item, use the key …

Update ANF APRL related to AZ

---

azure-resources/Sql/servers/kql/74c2491d-048b-0041-a140-935960220e20.kql

…935960220e20.kql
modified:   a bug in the query
[issue145](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues/145)
1. Modified azure-resources/Sql/servers/kql/74c2491d-048b-0041-a140-935960220e20.kql query to reflect the right result
-

Modified KQL query for Geo Replication

---

azure-resources/Network/virtualNetworkGateways/kql/1c34faa8-8b99-974c-adbf-71922eae943c.kql
azure-resources/RecoveryServices/vaults/kql/9e39919b-78af-4a0b-b70f-c548dae97c25.kql
azure-resources/Storage/storageAccounts/kql/1c34faa8-8b99-974c-adbf-71922eae943c.kql

Closes #159 and #161
/cc @alisakina99 @oZakari

Renamed query file to have a `.kql` suffix

---

azure-resources/Compute/virtualMachines/kql/d3f3ee41-b9aa-d34d-b442-5d46d20232b2.kql
azure-resources/Compute/virtualMachines/recommendations.yaml

Removed SSD recommendation based on PG feedback.
Customers should be advised to choose based on perf and availability requirements of a given workload, and we already have the APRL recommendation “Mission Critical Workloads should consider using Premium or Ultra Disks”.
1. Removed "Production VMs should be using SSD disks"

Removed SSD recommendation based on PG feedback

---

tools/1_wara_collector.ps1
tools/Version.json

BugFix on Cloudshell Execution
1. Bugfix on authentication errors when running the script from Cloudshell

Tooling: Bugfix on Cloudshell

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Adding recommendationTypeId for VirtualMachines to test wara scripts

Adding recommendationTypeId for VirtualMachines to test wara scripts

---

azure-resources/Compute/virtualMachineScaleSets/kql/83d61669-7bd6-9642-a305-175db8adcdf4.kql

ARG query message updated to correct format
None
1. Update ARG content to correct format
1. none

Fix incorrect ARG placeholder content

---

azure-specialized-workloads/sap/recommendations.yaml

Replace this with a brief description of what this Pull Request fixes, changes, etc.

Adding Advisor links for APRL-SAP checks

---

azure-resources/Network/privateDnsZones/recommendations.yaml

In https://github.com/basimolimajeed/Azure-Proactive-Resiliency-Library-v2/edit/main/azure-resources/Network/privateDnsZones/recommendations.yaml  The recommendation to _Monitor Private DNS Zones health and set up alerts_ (aprlGuid: ab896e8c-49b9-2c44-adec-98339aff7821) points to a learnMoreLink about Private DNS Scenarios which has nothing to do with monitoring.
A better name and url for the link are :
- name: Supported metrics for Microsoft.Network/privateDnsZones url: "https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-network-privatednszones-metrics
- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issue …

Update recommendations.yaml for Private DNS Zone Monitoring and Alerting

---

azure-resources/ApiManagement/service/kql/c79680ea-de85-44fa-a596-f31fa17a952f.kql
azure-resources/ApiManagement/service/recommendations.yaml
azure-resources/App/containerApps/kql/8dbcd94b-0948-4df3-b608-1946726c3abf.kql
azure-resources/App/containerApps/recommendations.yaml
azure-resources/ServiceBus/namespaces/kql/d810e3a8-600f-4be1-895b-1a93e61d37fd.kql
azure-resources/ServiceBus/namespaces/recommendations.yaml

Replace this with a brief description of what this Pull Request fixes, changes, etc.
1. Adds APIM item c79680ea-de85-44fa-a596-f31fa17a952f about auto-scale
2. Adds Service Bus item d810e3a8-600f-4be1-895b-1a93e61d37fd about auto-scale
3. Adds ACA item 8dbcd94b-0948-4df3-b608-1946726c3abf about health probes
N/A

Recommendation additions for APIM, Service Bus, and ACA

---

.gitignore
tools/1_wara_collector.ps1

Remove GUI

---

azure-resources/ContainerService/managedClusters/kql/005ccbbd-aeab-46ef-80bd-9bd4479412ec.kql
azure-resources/ContainerService/managedClusters/kql/269a9f1a-6675-460a-831e-b05a887a8c4b.kql
azure-resources/ContainerService/managedClusters/kql/5ee083cd-6ac3-4a83-8913-9549dd36cf56.kql
azure-resources/ContainerService/managedClusters/kql/7f7ae535-a5ba-4665-b7e0-c451dbdda01f.kql
azure-resources/ContainerService/managedClusters/kql/a7bfcc18-b0d8-4d37-81f3-8131ed8bead5.kql
azure-resources/DesktopVirtualization/hostPools/kql/979ff8be-5f3a-4d8e-9aa3-407ecdd6d6f7.kql
azure-resources/Insights/activityLogAlerts/kql/9729c89d-8118-41b4-a39b-e12468fa872b.kql
azure-resources/KeyVault/vaults/kql/00c3d2b0-ea6e-4c4b-89be-b78a35caeb51.kql
azure-resources/Network/applicationGateways/kql/8364fd0a-7c0e-e240-9d95-4bf965aec243.kql
azure-resources/Network/publicIPAddresses/kql/1adba190-5c4c-e646-8527-dd1b2a6d8b15.kql
azure-resources/RecoveryServices/vaults/kql/9e39919b-78af-4a0b-b70f-c548dae97c25.kql
azure-resources/Storage/storageAccounts/kql/dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql
azure-resources/Web/serverFarms/kql/07243659-4643-d44c-a1c6-07ac21635072.kql
azure-resources/Web/serverFarms/kql/88cb90c2-3b99-814b-9820-821a63f600dd.kql
azure-resources/Web/serverFarms/kql/b2113023-a553-2e41-9789-597e2fb54c31.kql
azure-specialized-workloads/avd/kql/0bf1a2bb-7617-4ab2-a784-e7ea40c5f01b.kql
azure-specialized-workloads/avd/kql/dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql

KQL files should consistently project to use `recommendationId` (not `recommendationID` or `recommendationid`) 
Closes #210

Made use of recommendationId consistent

---

azure-resources/NetApp/netAppAccounts/recommendations.yaml

Update ANF APRL wordings per ANF PM Jitesh Mani.
1. Category for "Standard Networking" to be "Scalability
2. Add "Failover is a manual process." to match with https://learn.microsoft.com/en-us/azure/azure-netapp-files/cross-region-replication-requirements-considerations and  https://learn.microsoft.com/en-us/azure/azure-netapp-files/cross-zone-replication-requirements-considerations to avoid confusion.
N/A

Update ANF APRL wordings per ANF PM Jitesh Mani

---

azure-resources/Network/virtualNetworkGateways/kql/292e6e8e-7795-4e82-857a-bb9ca08b330c.kql
azure-resources/Network/virtualNetworkGateways/recommendations.yaml

Added "Deploy zone-redundant ExpressRoute gateways with zone-redundant Public IP(s)" in Network\virtualNetworkGateways
Description/KQL is based on slight update on "Deploy zone-redundant VPN gateways with zone-redundant Public IP(s)" 4bae5a28-5cf4-40d9-bcf1-623d28f6d917
NA 
1. Add new recommendation for …

Added "Deploy zone-redundant ExpressRoute gateways with zone-redundant Public IP(s)" in Network\virtualNetworkGateways

---

azure-resources/Network/publicIPAddresses/kql/c4254c66-b8a5-47aa-82f6-e7d7fb418f47.kql
azure-resources/Network/publicIPAddresses/recommendations.yaml

Public IP addresses should be DDoS protected .
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x ] Updated relevant and associated …

Add DDoS protection to public IPs

---

azure-resources/Network/azureFirewalls/recommendations.yaml

Fixed the description of [Leverage Azure Policy inheritance model](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#leverage-azure-policy-inheritance-model) because **Azure Policy** and **Azure Firewall policy** are different.
None
None
- Tested with hugo on my local machine.

Fix description

---

azure-resources/Compute/virtualMachines/kql/302fda08-ee65-4fbe-a916-6dc0b33169c4.kql
azure-resources/Compute/virtualMachines/recommendations.yaml

Reserving compute capacity reservations should be considered with critical workloads, especially in Azure regions that are capacity constrained.
[AB#35813](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/35813)
N/A

Add: Capacity Reservations

---

tools/1_wara_collector.ps1
tools/2_wara_data_analyzer.ps1
tools/Version.json

dev-tools merge

---

azure-resources/App/_index.md
azure-resources/App/containerApps/_index.md
azure-resources/App/managedEnvironments/_index.md
azure-resources/AppConfiguration/_index.md
azure-resources/AppConfiguration/configurationStores/_index.md

Some services are not visible in the website's navigation.
[AB#35950](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/35950)
none

Update visibility of Azure resource

---

azure-resources/AAD/_index.md
azure-resources/AAD/domainServices/_index.md
azure-resources/AAD/domainServices/kql/a3058909-fcf8-4450-88b5-499f57449178.kql
azure-resources/AAD/domainServices/kql/bb6deb9d-24fa-4ee8-bc23-ac3ebc7fdf8e.kql
azure-resources/AAD/domainServices/recommendations.yaml

Adds recommendations for Entra Domain Services.
Closes #248 
none

Adds aad/domainServices recommendations

---

azure-resources/EventHub/namespaces/kql/84636c6c-b317-4722-b603-7b1ffc16384b.kql
azure-resources/EventHub/namespaces/recommendations.yaml
docs/content/contributing/create-content/create-recommendations/_index.md

- Updates recommendations after discussing with PG for EventHub.
- Remove duplicate query file
- Fixes datatype for automationAvailable in contribution guide
Fixes #17 
Fixes #249
1. None

Bug Fix - Update EventHub recommendations and remove duplicate query and datatype reference in docs for automationavailable

---

azure-resources/DBforMySQL/flexibleServers/recommendations.yaml
azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml

Verified ARG queries for OSS with Vandhana Mehta (MySQL) and Guy Bowerman (PostgreSQL), changed impact to High for read replicas as discussed.
MySQL
PostgreSQL
None
None

Verified queries supported by arg for OSS and changed impact to high for read replicas

---

docs/content/tools/script-overviews/_index.md

Added aka.ms download commands to the [tools document](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/tools/script-overviews/) for convenience.
I will update the aks.ms links owners to the same as the `aka.ms/aprl` owners after this PR merged.
```powershell
iwr https://aka.ms/aprl/tools/1 -out 1_wara_collector.ps1
iwr https://aka.ms/aprl/tools/2 -out 2_wara_data_analyzer.ps1
iwr https://aka.ms/aprl/tools/3 -out 3_wara_reports_generator.ps1
iwr https://aka.ms/aprl/tools/pptx -out 'Mandatory - Executive Summary presentation - Template.pptx'
iwr https://aka.ms/aprl/tools/docx -out 'Optional - Assessment Report - Template.docx'
```
None
None
- Built and checked the output on the local machine with hugo.

Add aka.ms download commands to tools doc

---

azure-resources/Compute/virtualMachines/kql/f0a97179-133a-6e4f-8a49-8a44da73ffce.kql
azure-resources/Compute/virtualMachines/recommendations.yaml

Add ARG query for Azure VM disk encryption recommendation (f0a97179-133a-6e4f-8a49-8a44da73ffce) :
None

Add ARG code for Azure VM disk encryption recommendation

---

tools/1_wara_collector.ps1
tools/Version.json

BugFix Subscriptions / Resource Group filtering

---

tools/1_wara_collector.ps1

BugFix Advisory Filtering

---

tools/1_wara_collector.ps1

BugFix Specialized Workloads not displaying the recommendation details in the Recommendation's sheet

Hotfix version

---

tools/1_wara_collector.ps1

BugFix RG Filtering

---

tools/1_wara_collector.ps1

Bringing dev-tools up to date with main

Devtools fix

---

tools/1_wara_collector.ps1

BugFix Tag Filtering

---

azure-resources/NetworkFunction/azureTrafficCollectors/kql/136eaa235-2985-4050-b08c-1cf519704d3a.kql
azure-resources/NetworkFunction/azureTrafficCollectors/recommendations.yaml

ExpressRoute Circuit has recently started supporting traffic collector. Added recommendation for ERTC. 
NA

Added recommendation for ExR Circuit

---

tools/1_wara_collector.ps1

BugFix on ResourceGroup Filtering

---

tools/1_wara_collector.ps1

Added parameter validation and validation functions.

ADD: Param validation for subid rgid tenantid

---

tools/1_wara_collector.ps1

BugFix Runbooks "N/A" resource IDs

---

tools/1_wara_collector.ps1

BugFix on Runbooks filtering

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Update AvSet migration recommendation to remove reference to update domain and change learn more link
#235 
1. None

feat: update AvSet migration recommendation

---

azure-resources/Network/networkWatchers/kql/a1317a0b-402d-4604-be40-a25a004ba171.kql
azure-resources/Network/networkWatchers/kql/bf0b7dbd-016d-458c-af99-70fcb03ad451.kql
azure-resources/Network/networkWatchers/recommendations.yaml

Recommendations for network watcher traffic analytics and NSG/VNET flow logs
NA
NA

Network watcher TA and flow logs

---

tools/1_wara_collector.ps1

Bugfix on Tag Validation

---

tools/1_wara_collector.ps1

BugFix on Tagged RG

---

azure-resources/Network/expressRouteGateways/recommendations.yaml

Removed the unnecessary pipe character at the end of the long description.
None
None
- Built and verified with Hugo on my local machine.

fix: Remove unnecessary pipe character

---

azure-resources/Network/expressRouteGateways/recommendations.yaml

Fixes ExpressRoute product name.
None
None
- Built and verified with Hugo on my local machine.

fix: ExpressRoute product name

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Fixes the disk type name in the description.
- None
- None
- Built and verified with Hugo on my local machine.

fix: Disk type name in description

---

docs/content/tools/collector/_index.md

Dev tools Doc updates

---

tools/1_wara_collector.ps1

BugFix Advisor Resource Filtering

---

azure-resources/Databricks/workspaces/recommendations.yaml

Removes unnecessary `?`.
- None
- None

fix: Remove unnecessary "?"

---

azure-resources/Databricks/workspaces/recommendations.yaml

Fixes an abbreviated product name. Should not use abbreviated product name.
- None
- None

fix: Fix abbreviated product name

---

azure-resources/EventHub/namespaces/recommendations.yaml

Fixes an abbreviated word. Should not use abbreviated words without the original words.
- None
- None

fix: Fix abbreviated word

---

azure-resources/DesktopVirtualization/hostPools/recommendations.yaml

Fixed the product name in description.
- None
- None

fix: Fix product name in description - FSLogix

---

tools/2_wara_data_analyzer.ps1

BugFix Advisor Recommendation

---

azure-resources/DesktopVirtualization/hostPools/recommendations.yaml
azure-resources/DesktopVirtualization/scalingPlans/recommendations.yaml

Adds the learn more link titles to the Desktop Virtualization recommendations.
- None
- None
**Example of the current learn more link title:**
- https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/DesktopVirtualization/hostPools/
**Example of after this PR:**

feat: Add learn more link titles to Desktop Virtualization recommendations

---

azure-resources/AVS/privateClouds/recommendations.yaml

Adds the learn more link titles to the AVS recommendations.
- None
- None

feat: Add learn more link titles to AVS recommendations

---

.github/dependabot.yml
.github/policies/resource-management.yml
azure-resources/Network/expressRouteGateways/recommendations.yaml

Updates resource management policy for new labels and adds new policies for adding labels depending upon titles. 
Also updates dependabot settings
1. None

build: Hygeine-dependabot

---

tools/1_wara_collector.ps1

Resource Sub Level Validation

---

docs/content/tools/analyzer/_index.md
docs/content/tools/collector/_index.md
docs/content/tools/reports/_index.md

Fix weight and titles of tools pages
N/A
None

fix: Fix weight and update titles

---

tools/1_wara_collector.ps1
tools/Version.json

BugFix Subscription Parameters
Fixes #372 
Resolves #372

fix: BugFix Subscription Parameters

---

tools/1_wara_collector.ps1

BugFix Runbooks

---

tools/2_wara_data_analyzer.ps1

Custom recommendations bugfix

---

docs/content/tools/reports/_index.md

Recovered the frequently asked questions section for 3_wara_reports_generator.ps1
**NOTE:** Also need to update the target URL of https://aka.ms/aprl/tools/faq 
- Fixes #375
- None

fix: Frequently asked questions section for 3_wara_reports_generator.ps1

---

azure-resources/Network/privateDnsZones/recommendations.yaml

Update APRL Private DNS Zones recommendations for clarity
Resolves #45 
Resolves #261
Resolves AB#35189

docs: Update Private DNS Zone guidance for clarity and specificity

---

azure-resources/Network/privateDnsZones/recommendations.yaml

fix: Fix typo

---

azure-specialized-workloads/sap/recommendations.yaml

Fixed typo (add period).
- None
- None

fix: Fix typo (add period)

---

docs/layouts/shortcodes/azure-resources-recommendationlist.html
docs/layouts/shortcodes/azure-specialized-workloads-recommendationlist.html
docs/layouts/shortcodes/azure-waf-recommendationlist.html

Adds the APRL GUID property to all of the recommendation pages.
Fixes [AB#37297](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/37297)
1. None

feat: Add guid to pages

---

azure-resources/ServiceBus/namespaces/kql/20057905-262c-49fe-a9be-49f423afb359.kql
azure-resources/ServiceBus/namespaces/kql/20057905-262c-49fe-a9be-49f423afb359.kql.upstream-dependency
azure-resources/ServiceBus/namespaces/recommendations.yaml

Update wording and query for Service Bus availability zones recommendation
None
1. None

docs: update service bus AZ recommendation

---

tools/3_wara_reports_generator.ps1

Rename parameter to: "GenerateCSV"

Parameter Rename

---

tools/3_wara_reports_generator.ps1

Adding Potential Benefits Column

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Fix Azure Boost recommendation description talking about a "first link below" not consistent with Microsoft deliverables for instance (Action Plan, Workload Review), ...
This current description can only work when consulting the APRL web page or reading `recommendations.yaml` content.
My suggestion for this : let's produce consistent descriptions whatever the UI from which they are read (Web Page, Code Content, Azure Advisor Review, Action Plan Excel spreadsheet, ...).

fix: Fix Azure Boost recommendation description

---

azure-specialized-workloads/avd/recommendations.yaml

Updating impact of AVD multi-region items (from medium to high).
NA
Examples:
NA
ADO items:
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/37025
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/37026
1. NA

docs: Updating impact of AVD multi-region items

---

.github/scripts/build-recommendation-object.ps1
.github/workflows/build-recommendation-object.yml

Add: Recommendation Object Script
Added workflow to generate a recommendation object json every night. 
Added script to pull all yaml and kql together into an object that can be exported to json.
Completes [AB#36915](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/36915)
None

feat: Recommendation Object Pipeline

---

azure-resources/Sql/servers/kql/de266d8a-a9f3-4cb9-be95-9306001fceea.kql
azure-resources/Sql/servers/recommendations.yaml

Add recommendation for using SQL Failover Group endpoint
None
1. None

docs: add sql failover group endpoint recommendation

---

.github/scripts/build-recommendation-object.ps1
.github/workflows/build-recommendation-object.yml
tools/data/recommendations.json

Fixes to the recommendation object creation pipeline.
Hydrates the initial recommendation object.
None

fix: recommendation object pipeline

---

tools/3_wara_reports_generator.ps1

Bugfix File not found issue when not using the full file path for the PPT and Word template file
Resolves #398 
ADO Reference:  37448

BugFix full file name

---

azure-resources/AVS/privateClouds/recommendations.yaml

Updated impact of two medium AVS/privateCloud recommendations to high.

feat: Updated impact of two medium AVS/privateCloud recommendations to high.

---

.github/workflows/build-recommendation-object.yml

Adds write permissions to pipeline to fix nightly build errors

fix: add write permission to pipeline

---

.github/workflows/scorecard.yml
CODEOWNERS
docs/layouts/shortcodes/azure-resources-recommendationlist.html
docs/layouts/shortcodes/azure-specialized-workloads-recommendationlist.html
docs/layouts/shortcodes/azure-waf-recommendationlist.html

Adds approvers for data services and their associated directories with codeowners file. Also, removes PGVerified data from APRL pages. Finally, fixes issue with scorecard workflow.
Fixes [AB#37556](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/37556)
Fixes [AB#37499](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/37499)
1. None

chore: Data codeowners and remove pg verified from pages

---

.github/workflows/build-recommendation-object.yml
.github/workflows/code-review.yml
.github/workflows/dependency-review.yml
.github/workflows/hugo-build-pr-check.yml
.github/workflows/hugo-site-build.yml
.github/workflows/scorecard.yml
.github/workflows/validate-queries.yml
docs/layouts/shortcodes/azure-resources-recommendationlist.html
docs/layouts/shortcodes/azure-specialized-workloads-recommendationlist.html
docs/layouts/shortcodes/azure-waf-recommendationlist.html

- Adds different approach to publish updated json object.
- Remove unneeded column in summary tables for pg verified
- Reducing scope of permissions for workflows and adding consistent formatting
N/A
None

chore: Hygeine workflows

---

azure-resources/Network/connections/kql/f6a14b32-a727-4ace-b5fa-7b1c6bdff402.kql
azure-resources/Network/connections/recommendations.yaml

Added KQL for ExpressRoute FastPath Connections.
The query will find all ExpressRoute Connections, verify if the Virtual Network Gateway is of the right SKU level to have the option to enable FastPath. It returns both ExpressRoute Gateway Bypass and Private Endpoint/Link FastPath properties to determine if both are enabled. This query will also return ALI, SAP, AVS, etc. ExpressRoute Circuit Connections as well.
None

feat: Added KQL for ExpressRoute FastPath Connections

---

tools/1_wara_collector.ps1

BugFix on Advisories

---

.github/scripts/build-recommendation-object.ps1
tools/data/recommendations.json

Add: New directories to object creation script
Update: recommendation object

Update: recommendation object

---

.github/actions-config/gh-ado-sync-config.json
.github/workflows/ado-sync-workitems.yml
.github/workflows/build-recommendation-object.yml

-Adds sync from GitHub issues to ADO work items.
-Fixes issues with build recommendations object workflow
None

feat: Add sync for GitHub issues to Azure DevOps Work items

---

azure-resources/Compute/virtualMachines/kql/587ca3e4-113b-4c4f-b4e0-92cd8d2065b6.kql
azure-resources/Compute/virtualMachines/recommendations.yaml

Added recommendation for On-Demand Capacity Reservations for DR regions
Resolves AB#[37598](https://dev.azure.com/CSUSolEng/Azure%20Infra%20Compute/_workitems/edit/37598)
None

feat: Added recommendation for On-Demand Capacity Reservations for DR regions

---

azure-resources/Web/serverFarms/recommendations.yaml
azure-resources/Web/sites/recommendations.yaml

PG verified on  8 recommendations and below recommendations impact is set to High
--Enable Health check for App Services
--Set minimum instance count to 2 for app service (note that this currently needs to be set to 3 for zone redundancy to be enabled, but will be lowered to 2 by end of year).
--Monitor Performance
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] …

feat: Updates with PG verified recommendations and upgraded 3 recommendations to impact to High

---

.github/workflows/validate-queries.yml
.github/workflows/validate-recommendations.yml

This pull request includes updates to the GitHub Actions workflows to improve the validation process for queries and recommendations. The most important changes include modifying the checkout reference for pull requests and adding a sanity check step.
Changes to validation workflows:
* [`.github/workflows/validate-queries.yml`](diffhunk://#diff-83e0ded7b58f710f1243f160ce972fb35207ec862fe23b6d9fb1d4e606c0c121L53-R58): Modified the checkout reference to use `refs/pull/${{ github.event.number }}/merge` and added a sanity check step to verify the pull request's head SHA.
* [`.github/workflows/validate-recommendations.yml`](diffhunk://#diff-795af3bc8f73e85739dea54a9bdb83a20cf5e52b4b3a5245a15d3d57ebc07282L26-L27): Removed the `ref` parameter from the checkout step.
None

fix: Adjust checkout tasks

---

.github/workflows/validate-queries.yml

Adds back PR KQL Validation workflow triggers with additional safety measures for triggering the workflow.
1. None

refactor: Add logic to PR to remove label whenever this workflow is run

---

tools/2_wara_data_analyzer.ps1
tools/Version.json

Resolved issue with blank lines appearing in WARA Analyzer files.
None

fix: blank lines in impactedresources column

---

tools/2_wara_data_analyzer.ps1

Bump version in analyzer script to align with version.json
Users reported downloading current version of analyzer script but showing it was out of date even though it isn't.

fix: update version in analyzer

---

azure-resources/Network/virtualRouters/_index.md
azure-resources/Network/virtualRouters/kql/2226d069-de5b-4ec1-ad26-3249f4ab1741.kql
azure-resources/Network/virtualRouters/kql/b8ff662a-ab74-4b6a-8301-d4dae002bc14.kql
azure-resources/Network/virtualRouters/recommendations.yaml

New APRL guidance for Azure Route Server. No ARG queries developed - guidance only.
AB#37773

feat: New APRL guidance for Azure Route Server

---

tools/2_wara_data_analyzer.ps1
tools/Version.json

Bugfix the following issues:
Closes #360 
Closes #546

fix: Outages breaking the 2_wara_data_analyzer script and Categories without spaces

---

azure-resources/RecoveryServices/vaults/kql/2912472d-0198-4bdc-aa90-37f145790edc.kql
azure-resources/RecoveryServices/vaults/recommendations.yaml

Remove ARG query for RSV recommendation returning incorrect results
Fixes #470 
1. None

fix: remove broken rsv recommendation ARG query

---

azure-resources/App/containerApps/recommendations.yaml
azure-resources/ContainerRegistry/registries/recommendations.yaml
azure-resources/ContainerService/managedClusters/recommendations.yaml

Updates to container related recommendations
[AB#37558](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/37558)
1. None

docs: updates to container recommendations

---

azure-resources/Cache/Redis/recommendations.yaml
azure-resources/EventGrid/topics/recommendations.yaml
azure-resources/Web/serverFarms/recommendations.yaml
azure-resources/Web/sites/recommendations.yaml

Disable non-reliability related recommendations for Redis, Event Grid, and App Services
[AB#37558](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/37558)
1. None

docs: disable non-reliability recommendations

---

azure-resources/Sql/managedInstances/recommendations.yaml
tools/data/recommendations.json

c9afeb1e-e706-4809-be4e-75d9fac708f2 and 9fad5392-b852-4807-9b6d-3f700ff9771a did not have the correct resource type for SQL Managed Instances.
None

fix: sql mi recommendations

---

azure-specialized-workloads/avd/recommendations.yaml

Updates APRL GUID: 9b2301af-9cac-4f1a-871a-f17475d01812 removing specificity for App Attach as FSLogix will avail of this as well.
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/38636
1. n/a

feat: Update AVD Recommendation

---

azure-resources/CognitiveServices/accounts/kql/61187af4-7d36-4b48-b16e-de78bef143a0.kql
azure-resources/CognitiveServices/accounts/recommendations.yaml

Recommend service is deployed in multiple regions for high availability/business continuity
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38361/
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ x] Ensured PR tests are …

docs: reccomendation AOAI multi-region deployment

---

azure-resources/ApiManagement/service/kql/af4f88cb-35e8-4371-b29e-3a32b1d2f40a.kql
azure-resources/ApiManagement/service/recommendations.yaml
tools/data/recommendations.json

Added new resiliency recommendations for API Management Service
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38368/

docs: Added new APRL recommendations for API Management

---

azure-resources/MachineLearningServices/registries/_index.md
azure-resources/MachineLearningServices/registries/kql/611c7c96-ac55-4ddf-909e-9eb70fd048b7.kql
azure-resources/MachineLearningServices/registries/recommendations.yaml

Added new APRL recommendations for Azure Machine learning registry
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38372/

docs: Added new APRL recommendations for Azure Machine learning registry

---

azure-resources/Network/dnsResolvers/recommendations.yaml

Fix Azure DNS Private Resolver recommendation.
- Fix capitalization.
- Fix service name. "**Private DNS** Resolvers" is not, "**DNS Private** Resolvers" is correct.
- Remove specific language part from the URL. The learn site automatically redirects to the correct language based on the user's browser settings.
- #578
- None

fix: Fix Azure DNS Private Resolver recommendation

---

azure-resources/CognitiveServices/accounts/recommendations.yaml
azure-resources/MachineLearningServices/workspaces/recommendations.yaml
azure-resources/Network/expressRouteGateways/recommendations.yaml
azure-resources/Network/p2sVpnGateways/recommendations.yaml
azure-resources/Network/virtualHubs/recommendations.yaml
azure-resources/Network/vpnGateways/recommendations.yaml

Fix YAML files formatting style consistency.
- Use `|` with longDescription if it is missing.
- Add a period at the end of the longDescription text if it is missing.
None
None

fix: Fix YAML file formatting style consistency

---

tools/data/recommendations.json

chore: object

---

azure-resources/Storage/storageAccounts/recommendations.yaml
tools/data/recommendations.json

Fix the duplicated slash in URL.
None
None

fix: Fix duplicated slash in URL

---

azure-resources/Network/virtualHubs/recommendations.yaml

- Change the YAML styling of the longDescription to consistency.
- None
- None

fix: YAML format styling - Virtual hubs

---

azure-resources/Network/vpnSites/recommendations.yaml

- Remove a period in the description.
- Change the YAML styling of the longDescription to consistency.
- Remove the double line breaks at the end of the file.
- None
-None

fix: YAML format styling - VPN sites

---

tools/3_wara_reports_generator.ps1

Removing csvExport parameter from Report Generator Script

Removing csvExport parameter

---

azure-resources/Search/searchServices/kql/b376281d-bfec-4695-8f90-9a44544fdfa4.kql
azure-resources/Search/searchServices/kql/dff62efe-c3a3-4621-98b3-c877c65cb195.kql
azure-resources/Search/searchServices/recommendations.yaml
azure-specialized-workloads/ai/kql/a6c8f3f3-199a-4a13-aaf0-eb51eed5352e.kql
azure-specialized-workloads/ai/recommendations.yaml

AB#38366 https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38366
AB#38367 https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38367
AB#38703 https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38703
- [X ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide

docs: aisearch resiliency recommendations

---

azure-resources/Search/searchServices/recommendations.yaml
azure-specialized-workloads/ai/recommendations.yaml

Fixes tag in recommendations.
- #634
- #627
None

fix: Fix recommendation tags

---

.github/scripts/schemas/aprl-schema.yaml
azure-resources/Network/bastionHosts/recommendations.yaml
azure-resources/Network/dnsResolvers/recommendations.yaml
azure-resources/Search/searchServices/recommendations.yaml
azure-specialized-workloads/ai/recommendations.yaml
azure-waf/reliability/recommendations.yaml

This PR addresses the need for the WAF tag to be added to the WAF recommendations so they are able to be filtered in the recommendation object.
- Added WAF tag to allowed tags in schema.
- Added WAF tag to all WAF recommendations.
Completes #AB39292
Completes #AB39291
None.

feat: Add WAF Tag to schema and update WAF recommendations with tag

---

docs/content/tools/collector/_index.md

Getting error duing redirection to "../analyzer/" page. No need "_index.md" to fix it.

docs: Update _index.md

---

azure-resources/ContainerService/managedClusters/recommendations.yaml

Disable recommendation to use Azure Linux on AKS
None
1. None

feat: disable AKS Azure Linux recommendation

---

docs/content/tools-preview/_index.md
docs/content/tools-preview/analyzer/_index.md

Add steps for using Expert Analysis spreadsheet produced by the analyzer module
[AB#39491](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/39491)
1. None

docs: add expert analysis spreadsheet steps

---

azure-resources/Network/privateDnsZones/kql/a2341513-2ab8-4aa1-b100-302e54640f18.kql
azure-resources/Network/privateDnsZones/recommendations.yaml

Add new guidance for Azure Private DNS zones - "Use virtual network links to link global Private DNS Zones to VNETs in two or more regions"
Resolves AB#34810

docs: New APRL guidance for Azure Private DNS zones

---

azure-waf/reliability/recommendations.yaml

WAF reliability pillar checklist RE:07 has been updated to remove the recommendations "Use background jobs" and "Handle transient faults". Removing corresponding APRL recommendations
#680 
1. None

docs: disable RE07 recommendations deleted from WAF

---

azure-resources/Cdn/profiles/recommendations.yaml
azure-resources/Compute/galleries/recommendations.yaml
azure-resources/NetApp/netAppAccounts/recommendations.yaml

fix: res type updates

---

azure-resources/Cdn/profiles/recommendations.yaml

Temporarily change automation available for recommendation 38f3d542-6de6-a44b-86c6-97e3be690281 until return resourceid matches resource type in the ARG resources table.
None

fix: disabled bad recommendation

---

docs/content/tools/collector/_index.md

Adds section in collector tooling documentation that addresses the issues with Resourcegraph 1.0.2 and a work around for non-commercial environments.

docs: Update documentation for ResourceGraph 1.0.2 issues

---

azure-resources/RecoveryServices/vaults/recommendations.yaml
azure-specialized-workloads/sap/recommendations.yaml

Updated an incorrect Advisor ID and a missing Advisor ID

fix: missing advisor IDs

---

azure-resources/AppConfiguration/configurationStores/recommendations.yaml
azure-resources/CognitiveServices/accounts/recommendations.yaml
azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml
azure-resources/Compute/virtualMachines/recommendations.yaml
azure-resources/ContainerService/managedClusters/recommendations.yaml
azure-resources/Databricks/workspaces/recommendations.yaml
azure-resources/DesktopVirtualization/hostPools/recommendations.yaml
azure-resources/OperationalInsights/workspaces/recommendations.yaml
azure-resources/Subscription/subscriptions/recommendations.yaml
azure-resources/Web/serverFarms/recommendations.yaml
azure-resources/Web/sites/recommendations.yaml
azure-specialized-workloads/avd/recommendations.yaml

Updated all recommendations with the category of Governance to OtherBestPractices to align with Advisor Reliability categoriescategories
Fixes [AB#40030](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/40030)

feat: updated all Governance categories to OtherBestPractices

---

azure-resources/Compute/virtualMachines/recommendations.yaml

Changed the recommendation category for IP forwarding recommendation
Changed the VM recommendation for IP forwarding to the recommendation category of "OtherBestPractices" so it can be integrated into advisor.
N/A
None
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)

feat: Update VM-recommendations.yaml

---

azure-resources/AVS/privateClouds/recommendations.yaml
azure-specialized-workloads/avs/recommendations.yaml

Updated category of security related AVS recommendations.

feat: Updated category of security related AVS recommendations.

---

azure-specialized-workloads/avd/recommendations.yaml

fix: AVD cleanup

---

azure-resources/Cdn/profiles/recommendations.yaml

This is an effort from DRI leads to move security recommendations from APRL to Defender for Cloud.
Fixes [AB#40219](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/40219)
No breaking changes
As part of this pull request I have removed 1 recommendation that belong to security: Restrict traffic to your origins
and Public IP addresses should have DDoS protection enabled.

refactor: Removing CDN security recommendations

---

azure-resources/Network/ddosProtectionPlans/recommendations.yaml

Updated the recommendation category to "Reliability > MonitoringAndAlerting"

docs: Update recommendations.yaml

---

azure-resources/ApiManagement/service/recommendations.yaml

APRL/Advisor Duplicate
APRL recommendation af4f88cb-35e8-4371-b29e-3a32b1d2f40a
Configure API management service in multiple Azure regions
and
Advisor Recommedation 2e4d65a3-1e77-4759-bcaa-13009484a97e
Deploy an Azure API Management instance to multiple Azure regions for increased service availability
are duplicates. Adjusting the recommendations YAML file with Advisor ID to prevent duplicate recommendations in WARA Analysis. 
- [x ] Associated it with relevant [GitHub …

fix: APRL/Advisor Duplicate

---

.github/workflows/codeql.yml

Trying this again
Trying to get the advanced codeql configuration to work correctly.

fix: codeql.yml2

---

azure-resources/Compute/virtualMachines/recommendations.yaml
azure-resources/ContainerService/managedClusters/recommendations.yaml
azure-resources/NetApp/netAppAccounts/recommendations.yaml
azure-resources/Network/virtualNetworkGateways/recommendations.yaml

Added Advisor ID's for AKS, VM, VPN Gateway & NetApp zone recommendations

feat: Updating Advisor ID's for recent zone recommendations

---

azure-resources/Network/privateDnsZones/kql/1e02335c-1f90-fd4e-a5a5-d359c7b22d70.kql
azure-resources/Network/privateDnsZones/recommendations.yaml

Remove **Use regional Private DNS Zones when there is a low recovery time objective (RTO) requirement** as it applies to an edge case and not all use cases.
Related to AB#33046

feat: Removal of 1e02335c-1f90-fd4e-a5a5-d359c7b22d70

---

azure-specialized-workloads/oracle/_index.md

fix: oracle exadata2

---

azure-resources/Network/loadBalancers/recommendations.yaml
azure-resources/Network/virtualNetworkGateways/recommendations.yaml
azure-resources/Web/serverFarms/recommendations.yaml

Updating recommendations with latest Advisor ID's onboarded during pilot

feat: Updating Advisor ID's for recommendations onboarded to Advisor
