Azure/Azure-Proactive-Resiliency-Library-v2

CODEOWNERS
Add aprl-wara-tools as owner of tools directory and add directories for aprl-networking ownership.
N/A
1. Updates to codeowners file for two teams
None
=> Update codeowners for wara tools and networking

docs/content/contributing/getting-started/_index.md
Fix the repository name in Contributor Guide.
None
1. Fixes the repository name in Contributor Guide.
None
=> Fix the repository name in Contributor Guide

azure-resources/ContainerService/managedClusters/kql/4f63619f-5001-439c-bacb-8de891287727.kql
Added a single zone pool to the coverage of the query to fix the issue #36.
- APRL recommendation: [Deploy AKS cluster across availability zones](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/ContainerService/managedClusters/#deploy-aks-cluster-across-availability-zones)
- #36 
1. Adds a single zone pool to the coverage of the query.
2. Changes param columns.
None
=> Fix: Deploy AKS cluster across availability zones

azure-resources/Compute/virtualMachines/kql/cfe22a65-b1db-fd41-9e8e-d573922709ae.kql
Excluded Trusted Launch VMs and Confidential VMs because Azure Site Recovery does not support Trusted Launch VMs and Confidential VMs.
- Azure Site Recovery does not support [Trusted Launch VM](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#unsupported-features) currently.
> Unsupported features
> - Azure Site Recovery
- Azure Site Recovery does not support [Confidential VM](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-vm-overview#feature-support) currently.
> Confidential VMs don't support:
> - Azure Site Recovery
- #44 
1. Excludes Trusted Launch VMs and Confidential VMs from the query result.
2. Simplifies the query a bit. 
None
**Query result:**
**All VMs in the environment:**
**Replication enabled all VMs:**
=> Fix: Exclude Trusted Launch VMs and Confidential VMs

azure-resources/Network/azureFirewalls/kql/1b2dbf4a-8a0b-5e4b-8f4e-3f758188910d.kql
Update AzFw DDoS protection query to address issue #42  https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#configure-ddos-protection-on-the-azure-firewall-vnet
#42 
1. Update query 1b2dbf4a-8a0b-5e4b-8f4e-3f758188910d
1. None
=> query fix for issue 42

azure-resources/Compute/virtualMachines/kql/fa0cf4f5-0b21-47b7-89a9-ee936f193ce1.kql, azure-resources/Compute/virtualMachines/recommendations.yaml
Added a new VM recommendation and query for "Use ZRS Disks or Protect LRS Disks from Availability Zone Failure" (fa0cf4f5-0b21-47b7-89a9-ee936f193ce1) after discussion and verification with Disk PM Bea Vincent and Ryan Draper. …
=> Add a new VM recommendation for ZRS Disk

azure-resources/Network/applicationGateways/recommendations.yaml
Updating description based on PGs recommendation.  App GW by default has a minimum of 2 instances so the recommendation should be around enabling autoscaling instead of a minimum instance count.
AB#34801
1. Updated description to fit the recommendation.
2.  Added information to long description
=> AGW: Update first recommendation for minimum instance count.

azure-resources/ContainerService/managedClusters/kql/5ee083cd-6ac3-4a83-8913-9549dd36cf56.kql, azure-resources/ContainerService/managedClusters/kql/a01afc4c-7439-4919-b2da-3565992ea2a7.kql, azure-resources/ContainerService/managedClusters/kql/ba3f7d17-9654-4038-b172-09f1b2569925.kql, azure-resources/ContainerService/managedClusters/recommendations.yaml
Added in new AKS item and revised existing ones according to PG feedback
1. Updates pgVerified to true for AKS items:
- 4f63619f-5001-439c-bacb-8de891287727
- 902c82ff-4910-4b61-942d-0d6ef7f39b67
- 269a9f1a-6675-460a-831e-b05a887a8c4b
- 0611251f-e70f-4243-8ddd-cfe894bec2e7 
- dcaf8128-94bd-4d53-9235-3a0371df6b74 
- 928fcc6f-5e9a-42d9-9bd4-260af42de2e5 
- cd6791b1-c60e-4b37-ac98-9897b1e6f4b8
- bcfe71f1-ebed-49e5-a84a-193b81ad5d27 
- 7f7ae535-a5ba-4665-b7e0-c451dbdda01f 
- 005ccbbd-aeab-46ef-80bd-9bd4479412ec 
- a08a06a0-e41a-4b99-83bb-69ce8bca54cb
2. Updated AKS item 928fcc6f-5e9a-42d9-9bd4-260af42de2e5 description to using Pod Topology spread constraints instead of affinity rules based on PG feedback
3. Updated AKS item bcfe71f1-ebed-49e5-a84a-193b81ad5d27 description wording based on PG …
=> AKS: Update AKS guidance based on PG feedback

tools/3_wara_reports_generator.ps1
I encountered an unexpected regression where previously resolved code issues have resurfaced.
For reference, I’ve included the link to a previous pull request that contains similar corrections:
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pull/69
1. To fix the loop count, `$count -lt 5` was replaced with `$count -le 5`.
=> Revised Loop Iteration Issue on Slide 16

azure-resources/ContainerService/managedClusters/recommendations.yaml
Changing verbiage of AKS pod scheduling on worker nodes
1. Changing verbiage of AKS pod scheduling on worker nodes
None
=> changing verbiage of AKS pod scheduling on worker nodes

azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml
The `azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml` file refers to a non-existing query, certainly because a section has been copied over from the `virtualMachines` section, without updating the aprlGuid and the query contents.
Closes #171 
YAML should consistently refer to a single resource type and point to an existing KQL file.
=> Closes #171

azure-resources/RecoveryServices/vaults/kql/1549b91f-2ea0-4d4f-ba2a-4596becbe3de.kql
Fixed the ARG query of [Opt-in to Cross Region Restore for all GRS Azure Recovery Services vaults](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/RecoveryServices/vaults/#opt-in-to-cross-region-restore-for-all-geo-redundant-storage-grs-azure-recovery-services-vaults)
- Fixes #179
1. Fixes the condition for cross region restore.
2. Adds storage replication type as a condition.
3. Addes params to the result.
None
There are four Recovery Services vaults in the subscription with different configurations (LRS, ZRS, GRS, GRS+CRR).
The fixed query returns only a GRS Recovery Services vault without CRR.
=> Fix "Opt-in to Cross Region Restore for all GRS Azure Recovery Services vaults"

azure-resources/Network/loadBalancers/kql/6d82d042-6d61-ad49-86f0-6a5455398081.kql
KQL fix for the load-balancer backend pools recommendation that attempts to correct an issue with Basic load balancer's not reporting correct results for backend pool counts.  This query counts the number of backend pool members by querying NIC's and aggregating their backend pool ID's to obtain a count.  This requires that the virtual machine members share the same scope as the load-balancer within the resource graph query.
While this is imperfect, it is better than the previous result of not finding any failures. If the virtual machines reside out of the scope, the query will continue to error and then they can be checked manually.
Fixes #46 
1. issue #46 - Corrects an issue where basic load balancer …
=> lb kql backend pool bug fix - fixes issue #46

tools/1_wara_collector.ps1
Fixed a bug in some RG filtering that was causing it not to work at all.
=> FIX: RG Filtering

azure-resources/AVS/privateClouds/kql/29d7a115-dfb6-4df1-9205-04824109548f.kql, azure-resources/AVS/privateClouds/kql/a5ef7c05-c611-4842-9af5-11efdc99123a.kql, azure-resources/AVS/privateClouds/kql/e0ac2f57-c8c0-4b8c-a7c8-19e5797828b5.kql, azure-resources/AVS/privateClouds/kql/f86355e3-de7c-4dad-8080-1b0b411e66c8.kql, azure-resources/AVS/privateClouds/kql/fa4ab927-bced-429a-971a-53350de7f14b.kql, azure-resources/AVS/privateClouds/kql/fcc2e257-23af-4c68-aac8-9cc03033c939.kql, azure-specialized-workloads/avs/kql/0943aa90-e3db-4c61-aef1-782b6a6a3881.kql, azure-specialized-workloads/avs/kql/6be9a543-cf82-4926-82ea-7e1f1ffaad80.kql, azure-specialized-workloads/avs/kql/6f573d60-be93-4f18-8016-42e923e3c05e.kql, azure-specialized-workloads/avs/kql/726abfe3-adae-4a6d-8eb8-4b27a7214ca1.kql, azure-specialized-workloads/avs/kql/91c84596-1c41-48fe-8d5e-3f817e6a273b.kql, azure-specialized-workloads/avs/kql/bce16eee-0933-4baa-ab4d-8d1bb5653fc2.kql, azure-specialized-workloads/avs/kql/bdac462a-2eda-4a67-887d-46d58f141afe.kql, azure-specialized-workloads/avs/kql/c2794660-ffd7-4da3-96ba-5d546b70b1c6.kql
Several KQL files for recommendations that cannot be validaded with arg were out of standard
Just adjusted the "cannot-be-validated-with-arg"
=> BugFix on AVS "cannot-be-validated-with-arg" off on defined standard

tools/3_wara_reports_generator.ps1
Improved the error message when the specified Excel file is encrypted to provide a hint for users. The current error message `Excel File not found` will mislead users.
The **3_wara_reports_generator.ps1** script will fail with the following error message if the Excel file has a sensitivity label (= encrypted).
The script says `Excel File not found`. But the Excel file actually exists. The script runs with `-Debugging` option then the following logs are generated.
```
The file is not an valid Package file. If the file is encrypted, please supply the password in the constructor.
```
```
OfficeApps - 2024-06-27 14:45:51 - Error - System.Management.Automation.MethodInvocationException: Exception calling "Load" with "1" argument(s): "The file is not an valid Package file. If the file is …
```
=> Improve error message in the 3_wara_reports_generator.ps1

azure-resources/Sql/servers/kql/7e7daec9-6a81-3546-a4cc-9aef72fec1f7.kql
Modify query to give correct results :Monitor your Azure SQL Database in Near Real-Time to Detect Reliability Incidents
The current query returns databases that have a monitor alert associated with it as well as those that do not have one.
Example: I have 2 databases : **testdb** and **nomonitorsql**. I have configured an alert for **testdb** but not for **nomonitorsql**. see the screenshots below:
If I run the existing query I get both databases (indicating that alerting is not set up on either), in addition to the master database.
With the proposed query I only get the database that does not have an alert, (in addition to master of course)
- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant …
=> Update 7e7daec9-6a81-3546-a4cc-9aef72fec1f7.kql Monitor your Azure SQL existing query does not return accurate results

tools/1_wara_collector.ps1, tools/2_wara_data_analyzer.ps1, tools/3_wara_reports_generator.ps1
* Improved parameter validation
* Debugged runbook support
* Added `#Requires -Version 7` directive to PS scripts
=> Cawatson dev tools cleanup

tools/1_wara_collector.ps1
* Script will automatically "fix" `-SubscriptionIds` passed in as a raw GUID. 
* `595ae217-8264-4ac6-a137-a2780131137b` >> `\subscriptions\595ae217-8264-4ac6-a137-a2780131137b`
* Added comment-based help support
* Can be accessed by either `Get-Help` or `-?` switch
* Removed superfluous `--Help` parameter and supporting function
* ⚠️  **NOTE:** Please review and confirm help messaging
* `--Help` parameter removed. Instead, using `Get-Help` or `-?` switch.
=> Added Get-Help support and --better SubscriptionIds validation

azure-resources/Databricks/workspaces/recommendations.yaml, azure-resources/EventHub/namespaces/recommendations.yaml, azure-specialized-workloads/avd/_index.md, azure-specialized-workloads/avd/kql/dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql, azure-specialized-workloads/sap/kql/b60ae773-9917-4bca-8a42-7cb45365a917.kql
Fixing various documented bugs. Also, fixing an undocumented bug where an EventHub recommendation was disabled when it should've active. 
- Fixes #246 
- Fixes #234 
- Fixes #233
1. Removed WAF recommendations from AVD as no longer including them for specialized workloads as they expected to be incorporated for all workloads.
=> General-bug fixes

azure-resources/Network/networkWatchers/recommendations.yaml
Fixes "Network Watcher" capitalization.
None
None
- Built and verified with Hugo on my local machine.
=> fix: "Network Watcher" capitalization

azure-resources/ContainerRegistry/registries/recommendations.yaml
Fixes the learn more URL because it is the URL for review (Can access it is FTE only).
- None
- None
=> fix: Fix learn more URL

azure-resources/Compute/virtualMachines/kql/5f7e8a12-3c4f-456b-919c-2e9adff98c38.kql, azure-resources/Compute/virtualMachines/recommendations.yaml
Adds recommendation to update Azure Linux Agent version.
Closes #229 
1. None
=> feat: Add new linux agent recommendation

azure-specialized-workloads/avd/recommendations.yaml
Add missing recommendationTypeId value for two recommendations
Fixes #325 
1. None
=> fix: add missing recommendationTypeId value

azure-specialized-workloads/avd/recommendations.yaml
Update 99bf5c94-aa68-4bb3-8b7f-45d1c5f09b5d 
Update d61f6ee8-de1b-4fd9-9ce3-316cfe11ee05
cc: @swathibhat1 
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/36374
=> docs: Update AVD recommendations

README.md
Fixes the OpenSSF Scorecard badge URI.
- Current
[![OpenSSF Scorecard](https://api.scorecard.dev/projects/github.com/Azure/ALZ-Bicep/badge)](https://scorecard.dev/viewer/?uri=github.com/Azure/ALZ-Bicep)
- Fixed
[![OpenSSF Scorecard](https://api.scorecard.dev/projects/github.com/Azure/Azure-Proactive-Resiliency-Library-v2/badge)](https://scorecard.dev/viewer/?uri=github.com/Azure/Azure-Proactive-Resiliency-Library-v2)
- None
- None
=> fix: OpenSSF Scorecard badge URI

tools/3_wara_reports_generator.ps1
Fixes the number of impacted resources in the slide 16.
- Fixes #316
- None
=> fix: Number of impacted resources in slide 16

azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
Removed ` | Microsoft Learn` from the learn more link name.
- None
- None
=> fix: Remove "| Microsoft Learn" from learn more link name

docs/themes/hugo-geekdoc/static/custom.css
Fixes the menu item label overflow issue when it has a long label.
- #315
- None
- Built and verify on my local machine with Hugo.
=> fix: Menu item label overflow when it has long label

azure-resources/Databricks/workspaces/recommendations.yaml
Fixes a typo in the learn more link URL.
- None
- None
=> fix: Fix typo in learn more link URL

azure-resources/Network/networkWatchers/recommendations.yaml
Fixed learn more links of [Enable Network Security Group and Virtual Network Flow Logs](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/networkWatchers/#enable-network-security-group-and-virtual-network-flow-logs).
- The existing learn more link is describe only NSG flow logs.
- The added learn more link is describe VNet flow logs.
- None
- None
=> fix: Fix learn more links

azure-resources/Cdn/profiles/recommendations.yaml, tools/2_wara_data_analyzer.ps1, tools/3_wara_reports_generator.ps1
Added a recommendation around avoiding using AFD classic to the recommendations list and added the Guid.KQL
AB#35190
https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/35190/
Breaking Changes
N/A
=> feat: AFD Recommendation added

tools/2_wara_data_analyzer.ps1
BugFix HighAvailability names in recommendation coming from Advisor
Fixes #360
=> BugFix HighAvailability

azure-resources/Network/expressRouteCircuits/kql/f902cf86-2b53-2942-abc2-781f4fb62be6.kql, azure-resources/Network/expressRouteCircuits/recommendations.yaml
Fix: Removing VPN as a failover option for ExpressRoute Circuits, critical workloads should all use dual Circuits.
=> fix: Removing VPN as a failover option for ExpressRoute Circuits - critical workloads should all use dual Circuits.

azure-resources/DocumentDB/databaseAccounts/kql/921631f6-ed59-49a5-94c1-f0f3ececa580.kql, azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
1. None
1. Added AZ recommendation for Cosmos DB
=> feat: Added AZ recommendation for Cosmos DB

tools/1_wara_collector.ps1
Added the RepoUrl parameter to specify custom ARPL repo URL.
Our team uses the [translated APRL contents into Japanese](https://github.com/tksh164/aprl-v2-ja) because customers in Japan strongly want to Japanese artifacts (Excel, PowerPoint, etc).
- None
- None
=> feat: [Collector] Add RepoUrl parameter for custom ARPL repo

docs/content/contributing/create-content/create-recommendations/_index.md, tools/data/recommendations.json
Fixes the example value of **recommendationResourceType** in the [Create Recommendations](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-recommendations/#recommendation-structure).
The current example value is **Storage Account**, but most recommendations have the value with the resource type format.
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/9cd5e4f6cf14fdcbf6a9b7ac89c31bde8dc94252/azure-resources/Storage/storageAccounts/recommendations.yaml#L6-L6
- None
- None
=> fix: Fix recommendationResourceType example value

azure-resources/ServiceBus/namespaces/kql/f075a1bd-de9e-4819-9a1d-1ac41037a74f.kql, azure-resources/ServiceBus/namespaces/recommendations.yaml
Adds a recommendation for the lower minimum TLS version of Service Bus namespaces.
- #420
- None
=> feat: Add recommendation for Service Bus minimum TLS version 

azure-resources/DBforPostgreSQL/flexibleServers/kql/2ab85a67-26be-4ed2-a0bb-101b2513ec63.kql
Initial ARG code "Find Database for PostgreSQL instances that are read replicas" but we're looking for "Database for PostgreSQL instances that do not have read replicas".
Before my fix 👇 
After my fix 👇
=> fix: arg code for PostgreSQL read replica detection

.github/workflows/validate-queries.yml
Refactoring the ARG Query Workflow to be manually triggered.
N/A
1. None
=> refactor: Reconfigure Validate ARG Query Workflow to be Manually Triggered

azure-resources/Sql/servers/kql/943c168a-2ec2-a94c-8015-85732a1b4859.kql
Master database should be excluded from "Auto Failover Groups can encompass one or multiple databases, usually used by the same app." recommendation result.
Before my fix 👇
After my fix 👇
=> fix: exclude master DB from failover group recommendation

azure-resources/Sql/servers/kql/74c2491d-048b-0041-a140-935960220e20.kql
Master database should be excluded from "Use Active Geo Replication to Create a Readable Secondary in Another Region" recommendation result.
Before my fix 👇
After my fix 👇
=> fix: exclude master DB from active geo rep recommendation

tools/3_wara_reports_generator.ps1, tools/Version.json
Fix the script file version of 3_wara_reports_generator.ps1 to 2.1.6.
- #488
- None
=> fix: Script file version of 3_wara_reports_generator.ps1 to 2.1.6

azure-resources/Network/trafficManagerProfiles/kql/1ad9d7b7-9692-1441-a8f4-93792efbe97a.kql, azure-resources/Network/trafficManagerProfiles/recommendations.yaml, azure-resources/Network/virtualNetworkGateways/kql/bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql, tools/data/recommendations.json
This fix is to prevent any issues with Advisor recommendations using Lower or Upper characters in its recommendation GUIDs.
It also adds a new query for traffic manager profiles, to identify profiles without at least two endpoints in different regions.
=> fix: Update Virtual Network Gateway query and add new query for TrafficManagerProfiles

.github/workflows/build-recommendation-object.yml, .github/workflows/validate-queries.yml
This pull request includes several changes to the GitHub Actions workflows, primarily focusing on making sure that all workflows that can check out forked branches have an environment approval. 
None
=> fix: Adjust workflow to require environment approval of PR before running specific workflows

azure-resources/Subscription/subscriptions/kql/9729c89d-8118-41b4-a39b-e12468fa872b.kql
We have detected a certain misalignment regarding the points of attention for this recommendation internally vs. APRL code. Indeed, the KQL code only *"return all subscriptions without Service Health alerts configured"* but we also need to materialize, in the “Impacted Resources” view of the action plan, all Service Health alert rules with a restricted configuration (specific services and/or regions and/or events). Let's take a look below:
Before, only subscriptions with non-existent Service Health rules were materialized. 
Now, subscriptions with non-existent Service Health rules AND Service Health alert rules with restricted configuration are returned by the code. This will automatically create these entries in the action plan for manual verification, as for other recommendations …
=> fix: incomplete Service Health alert check points

azure-resources/Web/sites/kql/0b80b67c-afbe-4988-ad58-a85a146b681e.kql
Updates query for 0b80b67c-afbe-4988-ad58-a85a146b681e to return a resourceid instead of a /config/web which we can't search in the WARA tooling.
Fixes #549 
No breaking changes.
=> fix: appservice query to return resourceid that is searchable

docs/content/tools/collector/_index.md
The https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/tools/collector/ page was referencing .\Wara_Collector.ps1 -configFile config.txt instead of .\1_Wara_Collector.ps1 -configFile config.txt
Old documentation
New documentation
=> docs: Fixed collector documentation

azure-resources/CognitiveServices/accounts/kql/081fc8a4-b2d9-405b-b351-334e621016f5.kql, azure-resources/CognitiveServices/accounts/recommendations.yaml
This is the APRL recommendation for AOAI on Global model deployment.
This recommendation is part of the ADO task
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_backlogs/backlog/Accelerator%20-%20AI%20Team/Stories/?workitem=38360
under ADO user story
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_backlogs/backlog/Accelerator%20-%20AI%20Team/Stories/?workitem=38215
Closes #AB38360 (https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_backlogs/backlog/Accelerator%20-%20AI%20Team/Stories/?workitem=38360)
Replace me
=> docs: APRL recommendations for Cog Services

azure-resources/ApiManagement/service/recommendations.yaml, azure-resources/Cdn/profiles/recommendations.yaml, azure-resources/Compute/virtualMachines/recommendations.yaml, azure-resources/DocumentDB/databaseAccounts/recommendations.yaml, azure-resources/KeyVault/vaults/recommendations.yaml, azure-resources/Network/applicationGateways/recommendations.yaml, azure-resources/RecoveryServices/vaults/recommendations.yaml, azure-resources/Storage/storageAccounts/recommendations.yaml, azure-resources/Web/sites/recommendations.yaml
Remove recommendationTypeId values for Advisor recommendations not in the reliability category.
None
1. None
=> docs: remove recommendationTypeId values for non-reliability Advisor recommendations

tools/1_wara_collector.ps1, tools/2_wara_data_analyzer.ps1, tools/Version.json
Updates for Collector and Analyzer script
The updates include:
- Including support for "Get-AzAccessToken -AsSecureString" 
- Bugfix on ResourceType sheet not considering the filtering attributes passed to the script
- Including support for "Specialized Workload" to support upcoming changes
- Include more than 15 Outages
Fixes #568
=> fix: Collector 2.1.18 & Analyzer 2.1.17

tools/2_wara_data_analyzer.ps1
Adjustment in the analyzer script to support the next specialized workload resource type standards
=> fix: Specialized Workload Resource Type Adjustment

.gitignore, tools/3_wara_reports_generator.ps1, tools/Version.json
Bumped the version in the `tools/3_wara_reports_generator.ps1` and `tools/Version.json` files to `2.1.7` for the `Generator` component.
Updated git ignore to exclude the APRL v2 directory.
None
=> fix: bump version and update ignore

azure-resources/Network/dnsResolvers/kql/bdd38c02-96bf-4d4e-a636-293729463f3d.kql, azure-resources/Network/dnsResolvers/recommendations.yaml
Created reccomendation and kql query for Private dns resolver
https://dev.azure.com/CSUSolEng/Accelerator%20-%20AI/_workitems/edit/38509/
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ x] Ensured PR tests are passing
- [ x] Performed testing and …
=> docs: reccomendation cross-region failover for Private DNS Resolver

azure-resources/Network/virtualNetworkGateways/kql/bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql
Query now returns `id` instead of `resId`
Fixes #605
=> fix:  Virtual Network Gateway (bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql) returns resId instead of id

azure-specialized-workloads/ai/_index.md
 
 
This PR adds a reference in the AI landing page in the specialized workloads section for App Service Availability Zone recommendation based on:
https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/azure-openai-baseline-landing-zone#workload-team-owned-resources
 
_"Azure App Service is used to host the example web application for the chat UI. In this architecture, it's also possible to use this service to host the containerized prompt flow for more control over the hosting environment that runs prompt flow. App Service has three instances, each in a different Azure zone."_
 
 
Fixes AB#38510
 
 
 
None
 
 
 
=> docs: added reference to availability zone for app service plans

azure-resources/Web/serverFarms/recommendations.yaml, tools/2_wara_data_analyzer.ps1, tools/Version.json
Fix disabled recommendations Recommendations unexpected appearing under ImpactedResources of Generated Action Plan.
Also fix an incorrect reference of the recommendation 855ca19a-6518-4f2e-9e5a-01796fbca9f8 for "serverFarm" instead of "sites"
Resolves #610
=> fix: fix on filtering ImpactedResources

azure-resources/Compute/virtualMachines/recommendations.yaml
Remove recommendationTypeId value for VM AZ recommendation. Advisor recommendation not returning expected results.
Fixes #569 
1. None
=> fix: remove recommendationTypeId value for VM AZ recommendation

azure-resources/Network/bastionHosts/recommendations.yaml, tools/data/recommendations.json
Deploy Azure Bastion across Availability Zones (c9b0c6f6-1f64-4b4b-8165-00770b295dd7) has two learn more links. So, remove a low relevant learn more link from the recommendation.
- #618
- None
=> fix: Remove low relevant learn more link

tools/2_wara_data_analyzer.ps1, tools/Version.json
Fix resource types not present in APRL being left out from ImpactedResources sheet
=> fix: fix on filtering resourcetypes on ImpactedResources

azure-resources/Network/expressRouteGateways/recommendations.yaml
- Change the YAML styling of the longDescription to consistency.
- Remove a low relevant learn more link.
- Remove the double line breaks at the end of the file.
- #618
- None
=> fix: ExpressRoute gateways recommendation

azure-resources/Insights/components/recommendations.yaml
Fix a recommendation YAML style for consistency.
- Added an empty line between recommendations.
- Removed verbose white-spaces.
- Fixed the product name.
- Removed the language specified part from the URL.
- #651
- None
=> fix: Fix recommendation YAML style

azure-resources/ApiManagement/service/recommendations.yaml, azure-resources/Batch/batchAccounts/recommendations.yaml, azure-resources/CognitiveServices/accounts/recommendations.yaml, azure-resources/MachineLearningServices/registries/recommendations.yaml, azure-resources/MachineLearningServices/workspaces/recommendations.yaml, azure-resources/Network/bastionHosts/recommendations.yaml, azure-specialized-workloads/ai/recommendations.yaml
Rework of AI tagging based on conversation with Eric and Kyle 
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated …
=> feat: update of AI-GPT tagging

azure-resources/Compute/virtualMachines/recommendations.yaml
Disable recommendation for VM monitoring with the Azure Montor agent. The query does not work properly, and the recommendation is redundant with other VM and WAF recommendations.
#363 
1. None
=> feat: disable VM monitor agent rec

azure-resources/Network/publicIPAddresses/recommendations.yaml
This is an effort from DRI leads to move security recommendations from APRL to Defender for Cloud.
Fixes [AB#40219](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/40219)
No breaking changes
=> refactor: Removing Public IP security recommendations

azure-resources/ContainerRegistry/registries/recommendations.yaml, azure-resources/ContainerService/managedClusters/recommendations.yaml
remove security as a recommendationcontrol for AKS and ACR and replace them with "OtherBestPractices"
=> chore: remove security as a recommendationcontrol for AKS and ACR

azure-resources/ContainerRegistry/registries/recommendations.yaml
2 recommendations were being returned for using premium tier container registry. 1 from APRL & 1 from Advisor. Added the recommendationTypeId from Advisor to APRL to remove both being returned by automation
=> fix: Update container registry recommendation with Advisor ID

.github/workflows/codeql.yml
Adds a custom yaml configuration for CodeQL to address PR issues.
- To associate an ADO Work Item (internal Microsoft team member), use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
=> fix: codeql merge blocking issues

.github/workflows/scorecard.yml
This PR fixes an issue where CodeQL was having 2 configurations, one unnamed and another as the correct advanced one.
=> fix: remove codeql default action from scorecard.

.github/scripts/schemas/aprl-schema.yaml
This PR adds Oracle to the list of allowed resource types in the APRL schema.
=> fix: oracle to aprl schema

azure-resources/Sql/servers/recommendations.yaml
Changed the SQL DB monitoring recommendation to disabled as per PG not accepting in Advisor
Fixes [AB#41015](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/41015)
=> fix: Moved SQL Monitoring recommendation to disabled

azure-specialized-workloads/oracle/_index.md
This PR changes the url for the specialized workload Oracle for cloudvmclusters:
=> fix: url path for oracle exadata

azure-resources/Network/virtualWans/_index.md
This pull request includes a small change to the `azure-resources/Network/virtualWans/_index.md` file. The change updates the `geekdocHidden` property from `false` to `true`, which hides VWAN as there are no recommendations.
1. None
=> fix: Hide vwan page as no recommendations

docs/layouts/shortcodes/azure-resources-recommendationlist.html
Added the Advisor's GUID to the recommendation details to easy to find corresponding Advisor's recommendation.
Easy to find the corresponding Advisor's recommendation from [Reliability recommendations](https://learn.microsoft.com/en-us/azure/advisor/advisor-reference-reliability-recommendations) by using the above GUID of the APRL pages.
None
None
=> feat: Add Advisor's GUID to recommendation details

azure-resources/ContainerService/managedClusters/kql/005ccbbd-aeab-46ef-80bd-9bd4479412ec.kql
Fixes to the manual scaling setting handling in 005ccbbd-aeab-46ef-80bd-9bd4479412ec.
- #749
- None
=> fix: Fix to manual scaling setting handling in 005ccbbd-aeab-46ef-80bd-9bd4479412ec

azure-resources/ContainerService/managedClusters/kql/7f7ae535-a5ba-4665-b7e0-c451dbdda01f.kql, azure-resources/ContainerService/managedClusters/recommendations.yaml
Fixes the recommended minimum node count for system node pools of AKS to three.
- [Architecture best practices for Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/well-architected/service-guides/azure-kubernetes-service#design-checklist)
> At a minimum, include two nodes for user node pools and **three** nodes for the system node pool.
- [Manage system node pools in Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli)
> If you run a single system node pool for your AKS cluster in a production environment, we recommend you use at least **three** nodes for the node pool.
> A minimum of **three** nodes of 8 vCPUs or two nodes of at least 16 vCPUs is recommended (for example, Standard_DS4_v2), especially for large …
=> fix: Fix recommended minimum node count for system node pools of AKS

azure-resources/Network/applicationGateways/kql/8364fd0a-7c0e-e240-9d95-4bf965aec243.kql, azure-resources/Network/applicationGateways/recommendations.yaml
This pull request updates the Application Gateway subnet size recommendation and refines the associated KQL query to better validate subnet configurations for scalability. The main changes clarify the minimum subnet size guidance and improve the logic for checking subnet prefixes.
* Updated the recommendation description in `recommendations.yaml` to clarify that a minimum subnet size of /24 is recommended for Application Gateway v2 subnets, including a more detailed explanation and benefits. The `recommendationTypeId` was also set.
* Refactored the KQL query in `8364fd0a-7c0e-e240-9d95-4bf965aec243.kql` to more accurately validate subnet prefixes by handling multiple address prefixes and ensuring the subnet prefix length is greater than /24 and not equal to /64.
NA
-->
NA
=> fix: Update app gw subnet recommendation to reflect Advisor recs.
